name: Example Deploy to Amazon ECS

on:
  push:
    branches:
      - "prod"

env:
  AWS_REGION: us-east-1                 
  ECR_REPOSITORY: 121731170468.dkr.ecr.us-east-1.amazonaws.com/learninfra
  ECS_SERVICE_WORKER: lks-worker-service
  ECS_SERVICE_VOTE: lks-vote-service
  ECS_SERVICE_RESULT: lks-result-service
  ECS_CLUSTER: learninfra
  WORKER_TASK_DEFINITION: ./worker/task-definition.json
  VOTE_TASK_DEFINITION: ./vote/task-definition.json
  RESULT_TASK_DEFINITION: ./result/task-definition.json
  WORKER_CONTAINER_NAME: lks-worker-container
  VOTE_CONTAINER_NAME: lks-vote-container
  RESULT_CONTAINER_NAME: lks-result-container
  ENV: "prod"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Example Deploy Application to Production
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Fill in the new image ID in the Amazon ECS task definition (worker)
      id: task-def-worker
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.WORKER_TASK_DEFINITION }}
        container-name: ${{ env.WORKER_CONTAINER_NAME }}
        image: 121731170468.dkr.ecr.us-east-1.amazonaws.com/learninfra:worker

    - name: Fill in the new image ID in the Amazon ECS task definition (vote)
      id: task-def-vote
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.VOTE_TASK_DEFINITION }}
        container-name: ${{ env.VOTE_CONTAINER_NAME }}
        image: 121731170468.dkr.ecr.us-east-1.amazonaws.com/learninfra:vote

    - name: Fill in the new image ID in the Amazon ECS task definition (result)
      id: task-def-result
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.RESULT_TASK_DEFINITION }}
        container-name: ${{ env.RESULT_CONTAINER_NAME }}
        image: 121731170468.dkr.ecr.us-east-1.amazonaws.com/learninfra:result

    - name: Deploy Amazon ECS task definition Worker
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-worker.outputs.task-definition }}  # Output task definition
        service: ${{ env.ECS_SERVICE_WORKER }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

    - name: Deploy Amazon ECS task definition vote
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-vote.outputs.task-definition }}  # Output task definition
        service: ${{ env.ECS_SERVICE_VOTE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

    - name: Deploy Amazon ECS task definition result
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-result.outputs.task-definition }}  # Output task definition
        service: ${{ env.ECS_SERVICE_RESULT }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
